#!/bin/bash
################################################################################
#  Licensed to the Apache Software Foundation (ASF) under one
#  or more contributor license agreements.  See the NOTICE file
#  distributed with this work for additional information
#  regarding copyright ownership.  The ASF licenses this file
#  to you under the Apache License, Version 2.0 (the
#  "License"); you may not use this file except in compliance
#  with the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
# limitations under the License.
################################################################################

rotateLogFile() {
    log=$1;
    num=9
    if [ -f "$log" -a "$num" -gt 0 ]; then
        while [ $num -gt 1 ]; do
            prev=`expr $num - 1`
            [ -f "$log.$prev" ] && mv "$log.$prev" "$log.$num"
            num=$prev
        done
        mv "$log" "$log.$num";
    fi
}

printUsage(){
    echo "usage: yoka [run <run_name> | shutdown | serve ]"
    echo "    run - runs a run file with performance tests"
    echo "    shutdown - shuts down a cloud experiment (if still running)"
    echo "    serve - opens a http server to serve the results directory"
}

printRunNames(){
    echo "Run names found:"
    for path in `ls runs/*.py` ; do
        name=`basename $path .py`
        echo "    $name"
    done
}

# change into yoka directory (if called from outside)
cd "`dirname "$0"`"

# create log dir
LOG_DIR="results/logs"
mkdir -p "$LOG_DIR"

if [ "$1" == "shutdown" ] ; then
    source env/bin/activate
    fab gcloud.delete_instances:True
elif [ "$1" == "run" ] ; then
    RUN_FILE="runs/$2.py"
    if  [ -e $RUN_FILE ] ; then

        LOG_FILE="$LOG_DIR/$2.stdout.log"
        # rotate log file in case another one exists
        rotateLogFile "$LOG_FILE"

        echo "$2 run file:" > "$LOG_FILE"
        echo "----------------------------" >> "$LOG_FILE"
        cat "$RUN_FILE" >> "$LOG_FILE"
        echo "----------------------------" >> "$LOG_FILE"

        source env/bin/activate
        export PYTHONPATH="$PYTHONPATH:`pwd`"
        python "$RUN_FILE" 2>&1 | tee -a "$LOG_FILE"
    else
        printUsage
        if [ "$2" != "" ] ; then
            echo
            echo "$2 is not a valid run name."
        fi
        echo
        printRunNames
        exit 1
    fi
elif [ "$1" == "serve" ] ; then
    source env/bin/activate
    export PYTHONPATH="$PYTHONPATH:`pwd`"
    cd results
    python "../core/web.py"
else
    printUsage
    echo
    printRunNames
    exit 1
fi
